### ISSUE TITLE
PC11: Create a class to handle json formatting for the method responses

### ISSUE THREAD

**Issue by tehvishesh** [CSE237SP2021/project-cooking#12]
Right now the main method in the Main.java class has some code for handling the response from getRandomRecipe and the exporting stuff that I think could go better in a separate class. Basically just move the code that's in Main that handles all the json writing and exporting into a different method and a different class and then call it in Main, just to clean up that file a bit and consolidate things better.

**Comment by DomBottom** [comment]
Satisfied by [Migrate JSON formatting/export functionality out of Main.java into the Exporter Class #16](https://github.com/CSE237SP2021/project-cooking/pull/16)
